spring:
  application:
    name: task-registry-service

  datasource:
    url: jdbc:postgresql://localhost:5432/registry
    username: registry
    password: registry
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html

token:
  signing:
    key: y62eU6bAB9ZPjXhFUl+W6cnBFISqKczbMQvjRyAsSGo=


server:
  port: 8080

logging:
  level:
    sql: info
    web: info
